name: Docker Image CI

on:
  push:
    branches:
      - main  # Change 'main' to the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Add your Docker Hub username in GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Add your Docker Hub password in GitHub Secrets

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./dockerfile  # Path to your Dockerfile
        push: true
        tags: txezio/nextquizz  # Replace with your Docker image name